from colorama import init
from colorama import Fore, Back, Style

import time

print(Fore.GREEN)

print(" _    _    _______    _____   _    _")
print("/ \  / \  /   _   \  /  ___\ / \  //")
print("| |  | |  |  [_]  |  | |     | | //")
print("| |==| |  | /   \ |  | |     | |/<")
print("| |  | |  | |   | |  | |___  | |\ \ ")
print("\_/  \_/  \_/   \_/  \_____/ \_/ \_\ ")

print("by Siri Wanna")

print(Fore.BLUE)

print('_______________________________________')
name = input("Name of victim | Имя атакуемого: ")
name1 = input('Lastname | Фамилия: ')
age = input("Bithyear | Год рождения: ")
data = input("Number of bithmouth | Номер месяца: ")
data1 = input("Number of bithday | Номер дня: ")

print(Fore.RED)

print("Обработка данных, подождите | Please wait...")
time.sleep(3)

print(Fore.YELLOW)

print(name + age)
time.sleep(1)
print(name1 + age)
time.sleep(1)
print(age + name)
time.sleep(1)
print(age + name1)
time.sleep(1)
print(name + name1)
time.sleep(1)
print(name1 + name)
time.sleep(1)
print(data + name)
time.sleep(1)
print(data + name1)
time.sleep(1)
print(age + data + data1 + name1)
time.sleep(1)
print(age + data1 + data + name)
time.sleep(1)
print(age + data1 + data + name1)
time.sleep(1)
print(name + data1 + data)
time.sleep(1)
print(name1 + data1 + data)
time.sleep(1)
print(name1 + data + data1)
time.sleep(1)
print(age + data1 + data)
time.sleep(1)
print(age + data + data1)
time.sleep(1)
print(age + data1 + data)
time.sleep(1)
print(data1 + data + age)
time.sleep(1)
print(data + age + data1)
time.sleep(1)
print(age + age)
time.sleep(1)
print(name + name)
time.sleep(1)
print(name1 + name1)
time.sleep(1)
print(data + age)
time.sleep(1)
print(data1 + age)
time.sleep(1)
print(data + data1 + age)
time.sleep(1)
print(age + data + data1 + name)
